[package]
name = "egomoose/priority-queue"
description = ""
repository = ""
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = ""
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]
private = true

[dependencies]

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"