[package]
name = "egomoose/priority-queue"
description = "A heap based priority queue where elements are served based on their priority rather than just insertion order."
repository = "https://github.com/EgoMoose/priority-queue-luau"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = ""
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]
private = true

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"